In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [7]:
df.sort_values("Year", ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [9]:
df.sort_values(["Year", "IMDb"])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [10]:
df2 = df.sort_values(["Year", "IMDb"]).copy()

In [11]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [21]:
df2.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,6,Hrithik Roshan,War,2019,Action,475,6.5
7,7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [22]:
df2.reset_index(drop=True)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [23]:
df2.reset_index(drop=True, inplace=True)

In [24]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [31]:
df2["Rank"] = df2["IMDb"].rank(ascending=False,method="dense")

In [32]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [33]:
df2 = df2[["Year", "Film", "Actor"]]

In [34]:
df2

    Year                      Film               Actor
0   2016                    Dangal          Aamir Khan
1   2017           Tiger Zinda Hai         Salman Khan
2   2017     Badrinath Ki Dulhania        Varun Dhawan
3   2018                 Padmaavat       Ranveer Singh
4   2018                     Stree       Rajkummar Rao
5   2018                 Andhadhun  Ayushmann Khurrana
6   2019                       War      Hrithik Roshan
7   2019                Good Newwz        Akshay Kumar
8   2019  Uri: The Surgical Strike       Vicky Kaushal
9   2022                Brahmastra       Ranbir Kapoor
10  2022         Bhool Bhulaiyaa 2       Kartik Aaryan
11  2023                   Pathaan      Shah Rukh Khan

In [39]:
df.rename(columns={"Film": "Film_Name"}, inplace=True)
df.rename(index={0: "Amir Khan", 2: "Amir Khot"}, inplace=True)

In [40]:
df

,Actor,Film_Name,Year,Genre,BoxOffice(INR Crore),IMDb
Amir Khan,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
Amir Khot,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
Amir Khot,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2